language: php
sudo: false

php:
        - 5.6
        - 5.5
        - 5.4

before_script: composer install --dev

script: cd src && (php -dshort_open_tag=On test.php -v --coveralls) && (php -dshort_open_tag=On test.php -v --deployed)

