language: php
sudo: false

php:
        - 5.6
        - 7.0

script:
        - if [ "$TRAVIS_PHP_VERSION" == "5.6" ]; then cd src && (php -dshort_open_tag=On test.php -v --baseline --coveralls) && (phpenv config-rm xdebug.ini) && (php -dshort_open_tag=On test.php -v --baseline --deployed) && php vendor/bin/coveralls -v; fi;
        - if [ "$TRAVIS_PHP_VERSION" == "7.0" ]; then cd src && (php -dshort_open_tag=On test.php -v --baseline) && (php -dshort_open_tag=On test.php -v --deployed --baseline); fi;
